/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogInIndexImport } from './routes/log-in/index'

// Create/Update Routes

const LogInIndexRoute = LogInIndexImport.update({
  path: '/log-in/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/log-in/': {
      id: '/log-in/'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/log-in': typeof LogInIndexRoute
}

export interface FileRoutesByTo {
  '/log-in': typeof LogInIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/log-in/': typeof LogInIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/log-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/log-in'
  id: '__root__' | '/log-in/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LogInIndexRoute: typeof LogInIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LogInIndexRoute: LogInIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/log-in/"
      ]
    },
    "/log-in/": {
      "filePath": "log-in/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
